Northwind.Web/Controllers/SwaggerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Northwind.Web.Controllers
{
    public class SwaggerController : Controller
    {
        // GET: Swagger
        public ActionResult Index()
        {
            return View();
        }
    }
}

Northwind.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>SCRIBE API</title>
        @*<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css" />*@
        <link href="~/Content/reset.css" rel="stylesheet" media="screen" />
        <link href="~/Content/reset.css" rel="stylesheet" media="print" /> 
        <!-- Bootstrap Core CSS -->
        <link href="~/Content/assets/bootstrap.min.css" rel="stylesheet" />
        
        <!-- Customizable CSS -->
        <link href="~/Content/assets/main.css" rel="stylesheet" data-skrollr-stylesheet>
        <link href="~/Content/assets/blue.css" rel="stylesheet" title="Color">
        <link href="~/Content/assets/animate.min.css" rel="stylesheet">
        
        <!-- Fonts -->
        <link href="http://fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">
        
        <!-- Icons/Glyphs -->
        <link href="~/Content/assets/fonts/fontello.css" rel="stylesheet">

        <!-- Favicon -->
        <link rel="shortcut icon" href="~/Content/assets/images/favicon.ico">

        <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
        <!--[if lt IE 9]>
        <script src="~/Scripts/theme/html5shiv.js"></script>
        <script src="~/Scripts/theme/respond.min.js"></script>
         <![endif]-->

        @RenderSection("head", required: false)
    </head>
    <body>
        <header>
            <div class="navbar">
                <div class="navbar-header">
                    <div class="container">

                        <ul class="info pull-left">
                            <li><a href="#"><i class="icon-mail-1 contact"></i> sales@scribesoft.com</a></li>
                            <li><i class=" icon-phone contact"></i>1.603.622.5109 x1</li>
                        </ul><!-- /.info -->

                        <ul class="social pull-right">
                            <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                            <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                        </ul><!-- /.social -->
                        <!-- ============================================================= LOGO MOBILE ============================================================= -->

                        <a class="navbar-brand" href="http://scribesoft.com"><img src="~/Content/assets/images/scribe-logo.png" class="logo" alt=""></a>

                        <!-- ============================================================= LOGO MOBILE : END ============================================================= -->

                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>

                    </div><!-- /.container -->
                </div><!-- /.navbar-header -->
                <div class="yamm">
                    <div class="navbar-collapse collapse">
                        <div class="container">
                            <!-- ============================================================= LOGO ============================================================= -->

                            <a class="navbar-brand" href="http://scribesoft.com"><img src="~/Content/assets/images/scribe-logo.png" class="logo" alt="Scribe"></a>

                            <!-- ============================================================= LOGO : END ============================================================= -->
                            <!-- ============================================================= MAIN NAVIGATION ============================================================= -->

                            <ul class="nav navbar-nav">
                                <li><a href="#">Overview</a></li>
                                <li>@Html.ActionLink("Endpoints", "Index", "Swagger")</li>
                                <li><a href="#">Release Notes</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- ============================================================= HEADER : END ============================================================= -->
        <!-- ============================================================= MAIN ============================================================= -->
        <main>
            @RenderBody()
        </main>
        <footer class="dark-bg">
            <div class="footer-bottom">
                <div class="container inner">
                    <p class="pull-left">© 2014 SCRIBE. All rights reserved.</p>
                    <ul class="footer-menu pull-right">
                        <li><a href="#">Overview</a></li>
                        <li><a href="#">Endpoints</a></li>
                        <li><a href="#">Release Notes</a></li>
                    </ul><!-- .footer-menu -->
                </div><!-- .container -->
            </div><!-- .footer-bottom -->
        </footer>
      
        <script src="~/Scripts/jquery-1.8.0.min.js"></script>
        <script src="~/Scripts/theme/skrollr.min.js"></script>
        <script src="~/Scripts/theme/skrollr.stylesheets.min.js"></script>
        <script src="~/Scripts/theme/waypoints.min.js"></script>
        <script src="~/Scripts/theme/waypoints-sticky.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/theme/bootstrap-hover-dropdown.min.js"></script>
        <script src="~/Scripts/theme/init.js"></script>
        @RenderSection("scripts", required: false)
    </body>
</html>